# Generated by Django 5.0.6 on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_notification_event_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoBaselineSnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=80, unique=True, verbose_name="Ключ снимка")),
                ("planning_year", models.PositiveIntegerField(verbose_name="Год планирования")),
                ("seed_value", models.IntegerField(blank=True, null=True, verbose_name="Seed")),
                ("payload", models.JSONField(blank=True, default=dict, verbose_name="Данные снимка")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Начальный снимок демо-данных",
                "verbose_name_plural": "Начальные снимки демо-данных",
                "db_table": "core_demo_baseline_snapshot",
                "ordering": ["key"],
            },
        ),
    ]
