# Generated by Django 5.0.6 on 2026-05-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_demobaselinesnapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoDataResetJob",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("token", models.CharField(max_length=96, unique=True, verbose_name="Токен статуса")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "В очереди"),
                            ("running", "Выполняется"),
                            ("succeeded", "Завершено"),
                            ("failed", "Ошибка"),
                        ],
                        default="queued",
                        max_length=24,
                        verbose_name="Статус",
                    ),
                ),
                ("seed_value", models.PositiveIntegerField(verbose_name="Seed")),
                ("progress_percent", models.PositiveSmallIntegerField(default=0, verbose_name="Прогресс")),
                ("stage_label", models.CharField(blank=True, default="", max_length=180, verbose_name="Текущий этап")),
                ("message", models.TextField(blank=True, default="", verbose_name="Сообщение")),
                ("error_message", models.TextField(blank=True, default="", verbose_name="Ошибка")),
                ("process_id", models.PositiveIntegerField(blank=True, null=True, verbose_name="PID процесса")),
                ("started_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата запуска")),
                ("finished_at", models.DateTimeField(blank=True, null=True, verbose_name="Дата завершения")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата обновления")),
            ],
            options={
                "verbose_name": "Задание пересоздания демо-данных",
                "verbose_name_plural": "Задания пересоздания демо-данных",
                "db_table": "core_demo_data_reset_job",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["status", "-created_at"], name="core_demo_job_status_idx"),
                ],
            },
        ),
    ]
