# Generated by Django 5.0.6 on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave", "0013_vacationurgentclosurerequest_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacationpreference",
            name="remainder_policy",
            field=models.CharField(
                choices=[
                    ("auto", "Можно распределить автоматически"),
                    ("approval", "Сначала согласовать со мной"),
                    ("defer", "Не планировать сверх указанного периода"),
                ],
                default="auto",
                max_length=24,
                verbose_name="Решение по остатку",
            ),
        ),
    ]
